-- 코드를 작성해주세요
WITH RECURSIVE REPORT_ECOLI AS (
    SELECT ID, PARENT_ID, 1 GENERATION FROM ECOLI_DATA WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT
        ed.ID
        , ed.PARENT_ID
        , GENERATION + 1
    FROM
        REPORT_ECOLI re
    JOIN ECOLI_DATA ed ON re.ID = ed.PARENT_ID
)

SELECT 
    COUNT(ID) AS COUNT
    , GENERATION
FROM
    REPORT_ECOLI
WHERE
    ID NOT IN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY
    GENERATION
ORDER BY
    GENERATION;