-- 세대 컬럼 추가 가상 테이블 생성
WITH RECURSIVE REPORT_ECOLI AS (
    SELECT ID, PARENT_ID, 1 DEPTH FROM ECOLI_DATA WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT 
        ED.ID
        , ED.PARENT_ID
        , DEPTH + 1
    FROM 
        REPORT_ECOLI RE
        JOIN ECOLI_DATA ED ON  RE.ID = ED.PARENT_ID
    WHERE DEPTH < 3
)
SELECT 
    ID 
FROM 
    REPORT_ECOLI 
WHERE 
    DEPTH = 3
ORDER BY
    ID;